#  _   _
#  | \ | |
#  |  \| | _____  ___   _ ___
#  | . ` |/ _ \ \/ / | | / __|
#  | |\  |  __/>  <| |_| \__ \
#  |_| \_|\___/_/\_\\__,_|___/

# Nexus - Config file
# (for plugin version V0.2)

# Dev Mode - When unable the plugin will be in developer mode
# This is used when developing Nexus to test features
dev-mode: true